name: Daily Stock Checker

on:
  schedule:
    - cron: '0 18 * * *'  # Her gün 18:00 UTC = 21:00 TRT
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  run-stock-check:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas numpy requests

      - name: Run Stock Checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Token: $TELEGRAM_BOT_TOKEN"
          echo "Chat ID: $TELEGRAM_CHAT_ID"
          python stock_diff_checker.py --token "$TELEGRAM_BOT_TOKEN" --chat-id "$TELEGRAM_CHAT_ID"